name: Bug report
description: Report a bug
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
      placeholder: What went wrong?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      placeholder: "1) Go to... 2) Click... 3) See error..."
  - type: input
    attributes:
      label: Expected Behavior
  - type: textarea
    attributes:
      label: Logs / Screenshots
  - type: input
    attributes:
      label: Environment (OS/Browser/Version)
