name: Feature request
description: Propose an improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Problem / Context
      placeholder: Why is this needed?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      placeholder: What do you suggest? Include UX or API sketches if useful.
  - type: textarea
    attributes:
      label: Alternatives
  - type: textarea
    attributes:
      label: Additional context
